### ISSUE TITLE
Icons with transparent background are displayed with black background

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChromeLabs/llama-pack#112]
I have a PWA with maskable icon with transparent background.

After I pack it using `llama-pack` the resulting TWA icon displays with black background.

I expected the white background (as WebAPK) or transparent (as in Chrome on desktop).

Is it ok?

I've checked the all icons in all `/app/src/main/res/` subfolders like `drawable-xxxhdpi`. All of them have the transparent background.

I'm not sure if the fact that my icon is maskable important or not.

**Comment by FluorescentHallucinogen** [comment]
Moreover, the resulting TWA icon looks adaptive (if I change the mask shape in Android setting, it changes correctly too). But for some reason there is no parallax visual effect (see https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive for more info).

The WebAPK icon is adaptive and has the parallax visual effect.

**Comment by andreban** [comment]
Could you share the link to the web manifest so we can repro?

**Comment by FluorescentHallucinogen** [comment]
`llama-pack init --manifest https://maskable-transparent-bg-bug.web.app/manifest.json`

**Comment by FluorescentHallucinogen** [comment]
> I'm not sure if the fact that my icon is maskable important or not.

Just checked, this is important. If I change `"purpose": "any maskable"` to `"purpose": "any"`, all is ok, app icon background color is white, not black.

**Comment by FluorescentHallucinogen** [comment]
@andreban Along the way, I've found another bug — #113.

**Comment by andreban** [comment]
Created #115 to track the parallax effect, as it seems a different issue from the background color.

**Comment by andreban** [comment]
It seems we're not support the `purpose` according to the [Web Manifest spec:](https://www.w3.org/TR/appmanifest/)

```
The purpose member is an unordered set of unique space-separated tokens that are ASCII case-insensitive. The allowed values are the icon purposes.
```

**Comment by andreban** [comment]
@rayankans FYI

**Comment by andreban** [comment]
llama-pack does find the maskable icon correctly when initialising the project. This is the output twa-manifest:

```json
{
  "packageId": "app.web.maskable_transparent_bg_bug.twa",
  "host": "maskable-transparent-bg-bug.web.app",
  "name": "Bug repro",
  "launcherName": "Bug repro",
  "themeColor": "#0080FF",
  "navigationColor": "#000000",
  "backgroundColor": "#FFFFFF",
  "enableNotifications": false,
  "startUrl": "/?utm_source=web_app_manifest",
  "iconUrl": "https://maskable-transparent-bg-bug.web.app/images/manifest/icon-1200x1200.png",
  "maskableIconUrl": "https://maskable-transparent-bg-bug.web.app/images/manifest/icon-1200x1200.png",
  "splashScreenFadeOutDuration": 300,
  "signingKey": {
    "alias": "android",
    "path": "./android.keystore"
  },
  "appVersionName": "1",
  "appVersionCode": 1,
  "shortcuts": [],
  "generatorApp": "llama-pack-cli",
  "webManifestUrl": "https://maskable-transparent-bg-bug.web.app/manifest.json",
  "appVersion": "1"
}
```

It seems the issue is in the template, not the project generation.

**Comment by NotWoods** [comment]
If you need a white background for your maskable icon, you should add a white background to the image. Maskable icons are not supposed to have transparency at all, so you'll see various methods to fill in the space depending on the browser.

**Comment by FluorescentHallucinogen** [comment]
The problem is that the app icon and the splash screen icon use the same image file (there is no way to set the different image for splash screen than for app icon, this is by design in the web app manifest spec). So I need the transparent background to avoid situations like this:

![screenshot](https://user-images.githubusercontent.com/7892779/75611225-a8ae3f80-5b29-11ea-96f4-741be5466526.png)

**Comment by FluorescentHallucinogen** [comment]
And like this (Chrome desktop Windows):

![chrome-desktop-windows](https://user-images.githubusercontent.com/7892779/75611339-c3cd7f00-5b2a-11ea-9aef-75a537aa7bb5.png)

**Comment by NotWoods** [comment]
You could have different icons for the maskable icon and not-maskable icon. I think Chrome will pick the "any" icon for the splash screen.
