### ISSUE TITLE
Building fails if the icon is less than 512x512

### ISSUE THREAD

**Issue by PEConn** [GoogleChromeLabs/llama-pack#12]
If you run the tool on a webapp that doesn't have an icon larger than 512x512, it won't work.

I don't think icons of that size are currently required for anything else, and I've found two major webapps that don't have such an icon (Pinterest and Instagram).

It would be good if we could either remove the need or let the user provide another image during `llama-pack init` instead of having to change their webapp manifest.

**Comment by andreban** [comment]
The icon is currently used for the following purposes, with the following sizes:

- Launcher icon: 48x48 to 192x192
- Store Icon: 512x512
- Splash Screens: 300x300 to 1200x1200

The code currently stretches smaller images to the required sizes. The concern is that by stretching we will generate lower quality splash screens and icons (which may already be the case for xxhdpi and xxxhdpi splash screens).

It seems to me that asking developers to provide an URL / file for an image with the appropriate size would be the right way to go.  We should also allow developers to choose different images for the launcher, splash screen and store icon.

**Comment by PEConn** [comment]
Maybe we could add a `--demo` flag or something that would just use a placeholder. Something really obvious that it's for demo purposes only, but still lets people play around with it quickly.

**Comment by andreban** [comment]
What about `--stretch-images`?

**Comment by PEConn** [comment]
I think if we had a `--demo` flag that used a high resolution placeholder image, it would create a high quality APK, but with something wrong that is obvious and the clearly the choice of the user. If we had a `--stretch-images` flag, I could see people using it, generating a poor quality APK (with stretched images), considering it good enough and just uploading it.

However, that's only a slight preference, I'd be happy with either.
