### ISSUE TITLE
Consider using jimp instead of sharp

### ISSUE THREAD

**Issue by NotWoods** [GoogleChromeLabs/llama-pack#16]
[sharp](https://www.npmjs.com/package/sharp) has native dependencies which can make it tricker to install llama-pack, while [jimp](https://www.npmjs.com/package/jimp) has no native dependencies and more capabilities. It makes installation much easier.

**Comment by andreban** [comment]
It seems the tradeoff here is ease of installation, compatibility and feature set vs performance. I did choose sharp for other projects in the past, based on performance.

For llama-pack, I think compatibility (specially cross-platform) and ease of installation is more important than performance, as we're generating a small set of images locally. So, `jimp` indeed looks like better choice.

Thanks for raising this.
