### ISSUE TITLE
Let an existing signing key be used

### ISSUE THREAD

**Issue by NotWoods** [GoogleChromeLabs/llama-pack#18]
Developers might have an existing key used for other apps. 

A simpler solution would be to have an option to skip generating a key.

**Comment by andreban** [comment]
Agreed. I'm thinking of a dialog like the following.

1. Ask the user for the path to the signing key, suggesting`./android.keystore` as the default.
2. Check if the keystore file already exists. 
3. If keystore file doesn't exist, ask user if they want to create it.
4. If yes, guide user through the questions to create the keystore and create it

We'll need to store the path to the keystore into a configuration file. Probably in the same file used in #11

**Comment by andreban** [comment]
Closed via #29
