### ISSUE TITLE
Use AndroidX

### ISSUE THREAD

**Issue by NotWoods** [GoogleChromeLabs/llama-pack#20]
The Android support packages have been moved to the `androidx.` namespace (from `android.support.`, in general). The old namespace has been deprecated and soon will no longer receive updates. Generating files using the AndroidX namespace will better future-proof the TWA apps.

**Comment by andreban** [comment]
Thanks for filing this. This is indeed in the roadmap. Here's more detail on why we didn't create it with AndroidX from the beginning: 

The template project is currently using `custom-tabs-client`, which is incompatible with AndroidX, even with Jetifier enabled.

We are working on an improved Library, https://github.com/GoogleChrome/android-browser-helper/, which uses AndroidX and is base on `androidx.browser`.

The `androidx.browser`version that `android-browser-helper` depends on hasn't been marked as stable yet and, therefore, `android-browser-helper` isn't stable either. We expect both to become stable still in Q4 and should update `llama-pack` to use those then.

**Comment by andreban** [comment]
`androidx.browser` 1.2.0, the version required by `android-browser-helper`, is now stable. Migrating `llama-pack` depends on https://github.com/GoogleChrome/android-browser-helper/issues/49

**Comment by andreban** [comment]
Closed via #55
