### ISSUE TITLE
Allow automating the build command.

### ISSUE THREAD

**Issue by PEConn** [GoogleChromeLabs/llama-pack#30]
Currently the `build` command asks for passwords interactively which makes it tricky for build to be run as part of an automated script.

We should allow passing the passwords as part of the command line invocation.

**Comment by andreban** [comment]
I'm some options here:

1. Users set the passwords in twa-manifest.json
2. Users set the passwords and environment variables
3. Both. Environment variables have precedence over twa-manifest.json?
