### ISSUE TITLE
Error Generating TWA - TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by JudahGabriel** [GoogleChromeLabs/llama-pack#36]
Hi guys,

Judah from Microsoft here. We're investigating integration of llama-pack into [PWABuilder](https://pwabuilder.com). 

I gave llama-pack a try on one of my personal PWA projects, and it throws an error during `llama-pack init`. Here's the command that throws the error:

`npm run llama-pack init --manifest https://messianicradio.com/manifest.json`

It throws this error:
```Fetching Manifest:  undefined
Error Genearating TWA TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Dev\llama-pack\node_modules\node-fetch\lib\index.js:1299:9)
    at C:\Dev\llama-pack\node_modules\node-fetch\lib\index.js:1404:19
    at new Promise (<anonymous>)
    at fetch (C:\Dev\llama-pack\node_modules\node-fetch\lib\index.js:1401:9)
    at Function.<anonymous> (C:\Dev\llama-pack\dist\lib\TwaManifest.js:212:50)
    at step (C:\Dev\llama-pack\dist\lib\TwaManifest.js:48:23)
    at Object.next (C:\Dev\llama-pack\dist\lib\TwaManifest.js:29:53)
    at C:\Dev\llama-pack\dist\lib\TwaManifest.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Dev\llama-pack\dist\lib\TwaManifest.js:19:12)
```

This is with Windows 10 Enterprise, JDK 8 from AdoptOpenJDK, and the latest Android command line tools.

**Comment by JudahGabriel** [comment]
Just tried on another PWA: https://webboard-app.web.app/manifest.json, same error, which makes me think I'm missing something. I'll try a few more.

**Comment by JudahGabriel** [comment]
Trying a few more things, I noticed when running this from PowerShell that manifest is undefined:

![image](https://user-images.githubusercontent.com/312936/69665326-0456c180-103f-11ea-82ac-6f6cf4664cec.png)
args
(Notice "fetching manifest undefined").

Doing some runtime debugging here in the script, I see that the init function has args, but args.manifest is undefined:

```js
async function init(args) {
  console.log('Fetching Manifest: ', args.manifest);
  // args.manifest is undefined. However, args._[1] is the manifest.
  ...
}
```

Heh. Any idea why args.manifest is undefined here?

**Comment by andreban** [comment]
This should be fixed in #37. Would you mind testing the instructions in the PR?

**Comment by JudahGabriel** [comment]
I'd be glad to test this today. Thanks Andre!

**Comment by andreban** [comment]
#39 updated README.md to up to date instructions

**Comment by andreban** [comment]
@JudahGabriel This seems to be fixed now. Please, re-open if it is still broken for you.
