### ISSUE TITLE
Hide URL bar

### ISSUE THREAD

**Issue by jesusprubio** [GoogleChromeLabs/llama-pack#48]
Hi, the tool works nice, thank you!

Is there any way to hide the navigation bar?

**Comment by andreban** [comment]
If you are seeing the URL bar, it's likely there's something not right with your Digital Asset Links configuration.

The [TWA Quick Start guide](https://developers.google.com/web/updates/2019/08/twas-quickstart#creating-your-asset-link-file) can help understanding this better and [Peter's Asset Link Tool ](https://play.google.com/store/apps/details?id=dev.conn.assetlinkstool) can help you get the correct file, based on your APK to deploy on `.well-known/assetlinks.json`.

**Comment by andreban** [comment]
Btw, we want llama-pack to help generating the correct `assetlinks.json` file too, and it's being tracked on #5

**Comment by jesusprubio** [comment]
Thank you! Solved 👌

**Comment by rajandimri** [comment]
I build the PWA for my Shopify store and Shopify doesn't provide the root access so that I can Put the Digital Asset Link in a file called assetlinks.json and upload it to your my website at .well-known/assetlinks.json (relative to the root).

How can I verify the digital asset link for Shopify?

:(

In the case of website verification for Google Webmaster Tool thet also provide a set of HTML tag that we insert in the theme.liquid header in shopify in this way we verify the domain with google web master tool.

and how to verify the digital assets link when we don't control the root domain?? 



Please help?

**Comment by justrealmilk** [comment]
Had the same issue. I thought following the instructions meant the fingerprints wouldn't change after deployment... But they did.

**Comment by mattkenefick** [comment]
It's already been resolved and the link above is good. The TLDR for `/.well-known/assetlinks.json` is this structure

```
[{
 "relation": ["delegate_permission/common.handle_all_urls"],
 "target": {
   "namespace": "android_app",
   "package_name": "com.your.package_name",
   "sha256_cert_fingerprints": [
     "XX:XX:XX:..."
   ]
 }
}]
```

Note that it wants the proper SHA256 structure with colons even though other fingerprints may not.

To get that fingerprint, you can run a command like this:

```
keytool -list -v -keystore /path/to/your/android.keystore -alias android -storepass YOUR_STORE_PASS -keypass YOUR_KEY_PASS
```

**Comment by ibrahimkarahan** [comment]
You can use Google's "Statement List Generator and Tester" tool to generate your assetlinks file:
https://developers.google.com/digital-asset-links/tools/generator

If you're using Play App Signing, you need to use Play Console to retrieve the SHA256 of the signing key. The key used by Bubblewrap to sign the package is called the "upload key" and will not match the "signing key" that Play uses for distribution. You can find it by following the direction under "Step 3: Register your app signing key with API providers" at this link:
https://support.google.com/googleplay/android-developer/answer/9842756?hl=en

**Comment by tanojericko** [comment]
thanks!! still works. App not available in playstore, good thing there is apk online
