### ISSUE TITLE
createTwaProject throwing error "ENOENT: no such file or directory"

### ISSUE THREAD

**Issue by JudahGabriel** [GoogleChromeLabs/llama-pack#58]
I'm using llama-pack as a library in a Node.js project. When I call

```js
twaGenerator.createTwaProject("d:/temp/llama", twaManifest);
```

I get lots of errors saying a file or directory doesn't exist, e.g.

```
(node:33288) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir 'd:\temp\llama\app\src\main\res\mipmap-mdpi'
```
![image](https://user-images.githubusercontent.com/312936/72117490-d1bd0b80-3302-11ea-90ab-3b73058a2c1d.png)

The end result is the TWA project generation doesn't succeed; it's missing a bunch of files. Looking in the target directory, I see an /app folder with a build.gradle in it, but nothing else; there is no /app/src folder, nor any /gradle folder.

I can workaround this by _manually_ creating these directories; at which point all the files get generated. But I'm wondering why the files aren't generated in the first place; the [TwaGenerator code looks](https://github.com/GoogleChromeLabs/llama-pack/blob/master/src/lib/TwaGenerator.js#L96) like it should be creating these directories. 

My full test code:

```js
router.get('/test', async function (req, res) {
  const rawManifestArgs = {
    packageId: "com.messianicradio",
    host: "https://messianicradio.com",
    name: "Chavah",
    themeColor: "#2f3d58",
    navigationColor: "#2f3d58",
    backgroundColor: "#2f3d58",
    startUrl: "/",
    iconUrl: "https://messianicradio.com/images/chavah512x512.png",
    maskableIconUrl: "https://messianicradio.com/images/chavah-maskable1000x1000.png",
    appVersion: '1.0.0',
    signingKey: {
      path: "C:/Users/judah/Documents/my-release-key.keystore",
      alias: 'alias_name',
    },
    useBrowserOnChromeOS: true,
    splashScreenFadeOutDuration: 300,
    enableNotifications: false,
    shortcuts: "[]",
  };
  const twaGenerator = new TwaGenerator();
  const twaManifest = new TwaManifest(rawManifestArgs);
  const targetDirectory = "d:\\temp\\llama";
  await twaGenerator.createTwaProject(targetDirectory, twaManifest);
});
```

**Comment by PEConn** [comment]
Have you run `npm install`?

(If that doesn't fix it I'll have a deeper look into the problem, it's just
that whenever I get an error like "ENOENT: no such file or directory" it's
because I forgot to run `npm install`)

**Comment by andreban** [comment]
The error seems to happen when trying to create the directories, on [this line][1]. I'm assuming that from the `mkdir` part of the error message (as there's also an issue with not handling the Promise rejection correctly on `Promise.app`, which makes it harder to get a stack-trace).

Can you confirm the NodeJS version being used? It seems the `recursive: true` option was only added on [`Node 10.12`][2], and not using recursive give us a [similar error][3];

[1]: https://github.com/GoogleChromeLabs/llama-pack/blob/master/src/lib/TwaGenerator.js#L101
[2]: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.12.0
[3]: https://stackoverflow.com/questions/28498296/enoent-no-such-file-or-directory-on-fs-mkdirsync

**Comment by JudahGabriel** [comment]
@andreban Thanks! I was working from home yesterday and sure enough, I have an older version (v6!) of node installed there. Trying this on my newer work laptop with the latest node installed indeed works.
