### ISSUE TITLE
Use name and short_name from the manifest

### ISSUE THREAD

**Issue by abdonrd** [GoogleChromeLabs/llama-pack#61]
I think that right now llama-pack only use the `short_name` to the Android project.

I want to propose to get both: `name` and `short_name`. And then...

- Use the `name` for the Android project, application name, etc.
https://github.com/GoogleChromeLabs/llama-pack/blob/252a03347f6421e6b94239784ea4b740211a830a/template_project/app/src/main/AndroidManifest.xml#L28

- Use the `short_name` just for the homescreen.
https://github.com/GoogleChromeLabs/llama-pack/blob/252a03347f6421e6b94239784ea4b740211a830a/template_project/app/src/main/AndroidManifest.xml#L41

**Comment by abdonrd** [comment]
Example:

<img width="903" alt="Screenshot 2020-01-14 at 17 58 53" src="https://user-images.githubusercontent.com/1007051/72364935-9c942d00-36f7-11ea-835a-532fc339b364.png">

**Comment by andreban** [comment]
When reading the Web Manifest, [we try to use the `short_name` and fallback to trying `name`, if the first is not available](https://github.com/GoogleChromeLabs/llama-pack/blob/master/src/lib/TwaManifest.ts#L205)

I think the proposal here is to have a different name for the launcher and the application in general. We're generally good with the idea, but we should probably use more descriptive names in the TWA Manifest.

My suggestion would be using `launcherName` for the name that will be used on the Android Launcher and `appName` for the name that is going to be used elsewhere.

- `launcherName` defaults to the `short_name` field on the Web Manifest and uses `name` if that is not availabl
- `appName` defaults to `name` on the WebManifest and uses `short_name` if that is not available.

We'd also need to change the CLI to allow developers to customise both.

**Comment by abdonrd** [comment]
Perfect! I love the idea! ❤️
