### ISSUE TITLE
The themeColor is used as backgroundColor

### ISSUE THREAD

**Issue by abdonrd** [GoogleChromeLabs/llama-pack#62]
I think is a bug, but the `themeColor` is used as `backgroundColor`.

**Comment by andreban** [comment]
I can reproduce. Here are the steps:

- Invoke `npx GoogleChromeLabs/llama-pack#0.3.0 init --manifest https://pwa-directory.appspot.com/manifest.json`
- Choose `red` for the status bar color.
- Choose `green` for the background color.

Expected Result:
- `twa-manifest.json` has `themeColor: #FF0000` and `backgroundColor: `#008000`.

Actual Result:
- `twa-manifest.json` has `themeColor: #FF0000` and `backgroundColor: `#FF0000`.
