### ISSUE TITLE
Add a generated-by meta-tag to the template project

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/llama-pack#77]
- This will help debugging APKs
- Should also include which version of the tool was used and the template version

@JudahGabriel I think it's worth making this customisable, so tools like PWA Builder cant set themselves as the generator. WDYT?

**Comment by JudahGabriel** [comment]
That'd be great, +1.

**Comment by andreban** [comment]
I'm thinking adding something like this the then AndroidManifest:

```xml
        <meta-data
            android:name="twa_generator"
            android:value="llama-pack"/>
```

If we need to add some kind of version, I'm inclined to use another meta-tag. (eg: `twa_generator_version`)

@PEConn WDYT?

**Comment by PEConn** [comment]
That seems fine to me Andre.

I've no particular preference as to whether we have generator name and
version as different pieces of meta data or have them merged together
somehow.
