### ISSUE TITLE
Add web_alternative flag and include web manifest for Chrome OS

### ISSUE THREAD

**Issue by PEConn** [GoogleChromeLabs/llama-pack#88]
Change the `cros_web_alternative` flag to something not Chrome OS specific and include the web app manifest in the raw resources to allow installation when without a network request.

Chrome side bug: https://crbug.com/1026230

**Comment by andreban** [comment]
This should also fix #52 when the Chrome OS feature lands.

**Comment by andreban** [comment]
@dominickng FYI

**Comment by PEConn** [comment]
Chromium side bug: https://crbug.com/1026230
